#!/bin/bash
# Tests for the Phase 2 menu-config persistence layer:
#   lib/state.sh::state_apply_menu_overrides / state_clear_menu_overrides
# Plus a round-trip of the file shape produced by menu_edit_config.

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

source lib/state.sh

ok()    { echo "  OK $1"; }
fail()  { echo "  FAIL $1"; }
chkeq() { [[ "$2" == "$3" ]] && ok "$1" || fail "$1 (got '$2', want '$3')"; }
chkrc() { [[ $2 -eq $3 ]] && ok "$1" || fail "$1 (rc=$2, want $3)"; }

TMPSTATE=$(mktemp -d)
trap "rm -rf $TMPSTATE" EXIT
export PATH_STATE="$TMPSTATE"

# ===========================================================================
echo "=== Test 1: apply is a no-op when the override file is missing ==="
unset RCONF_LOCALE
state_apply_menu_overrides
chkeq "no override file -> RCONF_LOCALE unset" "${RCONF_LOCALE:-<unset>}" "<unset>"

# ===========================================================================
echo
echo "=== Test 2: clear is a no-op when no file exists ==="
state_clear_menu_overrides; chkrc "no-op clear rc=0" $? 0

# ===========================================================================
echo
echo "=== Test 3: apply sources values from the override file ==="
cat > "$TMPSTATE/menu-config.sh" <<'EOF'
RCONF_LOCALE=en_GB.UTF-8
RCONF_TIME_ZONE=Europe/London
ZRAM_PERCENT_OF_RAM=75
EOF
unset RCONF_LOCALE RCONF_TIME_ZONE ZRAM_PERCENT_OF_RAM
state_apply_menu_overrides
chkeq "RCONF_LOCALE applied"        "$RCONF_LOCALE"        "en_GB.UTF-8"
chkeq "RCONF_TIME_ZONE applied"     "$RCONF_TIME_ZONE"     "Europe/London"
chkeq "ZRAM_PERCENT_OF_RAM applied" "$ZRAM_PERCENT_OF_RAM" "75"

# ===========================================================================
echo
echo "=== Test 4: overrides win over baseline values ==="
RCONF_LOCALE="baseline-default"
state_apply_menu_overrides
chkeq "override wins" "$RCONF_LOCALE" "en_GB.UTF-8"

# ===========================================================================
echo
echo "=== Test 5: clear removes the override file ==="
[[ -f $TMPSTATE/menu-config.sh ]] && ok "file present before clear"
state_clear_menu_overrides
[[ ! -f $TMPSTATE/menu-config.sh ]] && ok "file removed after clear" || fail "file still present"

# ===========================================================================
echo
echo "=== Test 6: round-trip values containing spaces and metacharacters ==="
# This mirrors what menu_edit_config writes: printf '%s=%q\n' for safe quoting.
declare -A current=(
  [SIMPLE]="hello"
  [WITH_SPACES]="two words"
  [WITH_QUOTES]='he said "hi"'
  [WITH_SHELL_META]='$(rm -rf /)'
  [EMPTY_VAL]=""
)
{
  echo "# Generated by installicious menu_edit_config — runtime overrides for the current run."
  for key in "${!current[@]}"; do
    printf '%s=%q\n' "$key" "${current[$key]}"
  done
} > "$TMPSTATE/menu-config.sh"

unset SIMPLE WITH_SPACES WITH_QUOTES WITH_SHELL_META EMPTY_VAL
state_apply_menu_overrides
chkeq "SIMPLE round-trip"         "$SIMPLE"          "hello"
chkeq "WITH_SPACES round-trip"    "$WITH_SPACES"     "two words"
chkeq "WITH_QUOTES round-trip"    "$WITH_QUOTES"     'he said "hi"'
chkeq "WITH_SHELL_META preserved" "$WITH_SHELL_META" '$(rm -rf /)'
chkeq "EMPTY_VAL round-trip"      "${EMPTY_VAL-unset}" ""

state_clear_menu_overrides

# ===========================================================================
echo
echo "=== Test 7: PATH_STATE fallback when not exported ==="
saved_path_state="$PATH_STATE"
unset PATH_STATE
mkdir -p state
echo 'FALLBACK_TEST="ok"' > state/menu-config.sh
unset FALLBACK_TEST
state_apply_menu_overrides
chkeq "fallback PATH_STATE=state" "$FALLBACK_TEST" "ok"
rm -f state/menu-config.sh
rmdir state 2>/dev/null
export PATH_STATE="$saved_path_state"

echo
echo "=== Done ==="
