#!/bin/bash
# Tests for the Phase 2 menu-config persistence layer:
#   lib/state.sh::state_apply_menu_overrides / state_clear_menu_overrides
# Plus a round-trip of the file shape produced by menu_edit_config.

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

source lib/state.sh
source lib/menu.sh

ok()    { echo "  OK $1"; }
fail()  { echo "  FAIL $1"; }
chkeq() { [[ "$2" == "$3" ]] && ok "$1" || fail "$1 (got '$2', want '$3')"; }
chkrc() { [[ $2 -eq $3 ]] && ok "$1" || fail "$1 (rc=$2, want $3)"; }

TMPSTATE=$(mktemp -d)
trap "rm -rf $TMPSTATE" EXIT
export PATH_STATE="$TMPSTATE"

# ===========================================================================
echo "=== Test 1: apply is a no-op when the override file is missing ==="
unset RCONF_LOCALE
state_apply_menu_overrides
chkeq "no override file -> RCONF_LOCALE unset" "${RCONF_LOCALE:-<unset>}" "<unset>"

# ===========================================================================
echo
echo "=== Test 2: clear is a no-op when no file exists ==="
state_clear_menu_overrides; chkrc "no-op clear rc=0" $? 0

# ===========================================================================
echo
echo "=== Test 3: apply sources values from the override file ==="
cat > "$TMPSTATE/menu-config.sh" <<'EOF'
RCONF_LOCALE=en_GB.UTF-8
RCONF_TIME_ZONE=Europe/London
ZRAM_PERCENT_OF_RAM=75
EOF
unset RCONF_LOCALE RCONF_TIME_ZONE ZRAM_PERCENT_OF_RAM
state_apply_menu_overrides
chkeq "RCONF_LOCALE applied"        "$RCONF_LOCALE"        "en_GB.UTF-8"
chkeq "RCONF_TIME_ZONE applied"     "$RCONF_TIME_ZONE"     "Europe/London"
chkeq "ZRAM_PERCENT_OF_RAM applied" "$ZRAM_PERCENT_OF_RAM" "75"

# ===========================================================================
echo
echo "=== Test 4: overrides win over baseline values ==="
RCONF_LOCALE="baseline-default"
state_apply_menu_overrides
chkeq "override wins" "$RCONF_LOCALE" "en_GB.UTF-8"

# ===========================================================================
echo
echo "=== Test 5: clear removes the override file ==="
[[ -f $TMPSTATE/menu-config.sh ]] && ok "file present before clear"
state_clear_menu_overrides
[[ ! -f $TMPSTATE/menu-config.sh ]] && ok "file removed after clear" || fail "file still present"

# ===========================================================================
echo
echo "=== Test 6: round-trip values containing spaces and metacharacters ==="
# This mirrors what menu_edit_config writes: printf '%s=%q\n' for safe quoting.
declare -A current=(
  [SIMPLE]="hello"
  [WITH_SPACES]="two words"
  [WITH_QUOTES]='he said "hi"'
  [WITH_SHELL_META]='$(rm -rf /)'
  [EMPTY_VAL]=""
)
{
  echo "# Generated by installicious menu_edit_config — runtime overrides for the current run."
  for key in "${!current[@]}"; do
    printf '%s=%q\n' "$key" "${current[$key]}"
  done
} > "$TMPSTATE/menu-config.sh"

unset SIMPLE WITH_SPACES WITH_QUOTES WITH_SHELL_META EMPTY_VAL
state_apply_menu_overrides
chkeq "SIMPLE round-trip"         "$SIMPLE"          "hello"
chkeq "WITH_SPACES round-trip"    "$WITH_SPACES"     "two words"
chkeq "WITH_QUOTES round-trip"    "$WITH_QUOTES"     'he said "hi"'
chkeq "WITH_SHELL_META preserved" "$WITH_SHELL_META" '$(rm -rf /)'
chkeq "EMPTY_VAL round-trip"      "${EMPTY_VAL-unset}" ""

state_clear_menu_overrides

# ===========================================================================
echo
echo "=== Test 7: chain precedence — role config overrides feature config ==="
# Simulates the source order menu_edit_config builds:
#   installicious.config  →  feature*.config  →  role*.config  →  menu-config.sh
# A key present in both feature.config and role.config must resolve to the
# role value (the rule is "role overrides feature").
TMPCFG=$(mktemp -d)
cat > "$TMPCFG/installicious.config" <<'EOF'
SHARED_KEY="from_installicious"
FEATURE_ONLY="from_installicious"
EOF
cat > "$TMPCFG/feature.config" <<'EOF'
SHARED_KEY="from_feature"
FEATURE_ONLY="from_feature"
ROLE_ONLY=""
EOF
cat > "$TMPCFG/role.config" <<'EOF'
SHARED_KEY="from_role"
ROLE_ONLY="from_role"
EOF

chkeq "feature-only key resolves to feature value" \
  "$(_menu_read_var_chain FEATURE_ONLY "$TMPCFG/installicious.config" "$TMPCFG/feature.config" "$TMPCFG/role.config")" \
  "from_feature"

chkeq "role-only key resolves to role value" \
  "$(_menu_read_var_chain ROLE_ONLY "$TMPCFG/installicious.config" "$TMPCFG/feature.config" "$TMPCFG/role.config")" \
  "from_role"

chkeq "shared key resolves to ROLE value (role wins)" \
  "$(_menu_read_var_chain SHARED_KEY "$TMPCFG/installicious.config" "$TMPCFG/feature.config" "$TMPCFG/role.config")" \
  "from_role"

# menu-config.sh wins over everything when present.
echo 'SHARED_KEY="from_user_edit"' > "$TMPSTATE/menu-config.sh"
chkeq "menu-config.sh overrides role value" \
  "$(_menu_read_var_chain SHARED_KEY "$TMPCFG/installicious.config" "$TMPCFG/feature.config" "$TMPCFG/role.config")" \
  "from_user_edit"
rm -rf "$TMPCFG"
state_clear_menu_overrides

# ===========================================================================
echo
echo "=== Test 8: menu-config.sh persists across simulated runs ==="
# Locks in the "edit once, keep forever" behavior: state_apply_menu_overrides
# must read previously-saved values without any framework helper clearing
# the file. The only way to wipe overrides is the explicit
# state_clear_menu_overrides call (or `rm` on the file).
rm -f "$TMPSTATE/menu-config.sh"
# Run-1: user enters values via the editor. menu_edit_config (whiptail-driven)
# can't be tested directly here, so we simulate its persistence step.
{
  echo "# Generated by installicious menu_edit_config — simulated for test."
  printf '%s=%q\n' "MOTD_WEATHER_API_KEY" "secret-bearer-abc123"
  printf '%s=%q\n' "MOTD_NAME" "alice"
} > "$TMPSTATE/menu-config.sh"

# Simulate end-of-run-1: nothing in the framework should auto-clear.
[[ -f "$TMPSTATE/menu-config.sh" ]] && ok "file present after run-1 (no auto-clear)" \
  || fail "menu-config.sh missing — something cleared it automatically"

# Run-2 startup: state_apply_menu_overrides should reload the values.
unset MOTD_WEATHER_API_KEY MOTD_NAME
state_apply_menu_overrides
chkeq "API key persisted across run"   "$MOTD_WEATHER_API_KEY" "secret-bearer-abc123"
chkeq "MOTD_NAME persisted across run" "$MOTD_NAME"            "alice"

# Manual reset still works on demand.
state_clear_menu_overrides
[[ ! -f "$TMPSTATE/menu-config.sh" ]] && ok "explicit clear removes file" \
  || fail "explicit clear did not remove file"

# ===========================================================================
echo
echo "=== Test 9: PATH_STATE fallback when not exported ==="
saved_path_state="$PATH_STATE"
unset PATH_STATE
mkdir -p state
echo 'FALLBACK_TEST="ok"' > state/menu-config.sh
unset FALLBACK_TEST
state_apply_menu_overrides
chkeq "fallback PATH_STATE=state" "$FALLBACK_TEST" "ok"
rm -f state/menu-config.sh
rmdir state 2>/dev/null
export PATH_STATE="$saved_path_state"

echo
echo "=== Done ==="
