#!/bin/bash
# Tests for the Phase 2 menu-config persistence layer:
#   lib/state.sh::state_apply_menu_overrides / state_clear_menu_overrides
# Plus a round-trip of the file shape produced by menu_edit_config.

cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1

source lib/state.sh
source lib/menu.sh

ok()    { echo "  OK $1"; }
fail()  { echo "  FAIL $1"; }
chkeq() { [[ "$2" == "$3" ]] && ok "$1" || fail "$1 (got '$2', want '$3')"; }
chkrc() { [[ $2 -eq $3 ]] && ok "$1" || fail "$1 (rc=$2, want $3)"; }

TMPSTATE=$(mktemp -d)
trap "rm -rf $TMPSTATE" EXIT
export PATH_STATE="$TMPSTATE"

# ===========================================================================
echo "=== Test 1: apply is a no-op when the override file is missing ==="
unset RCONF_LOCALE
state_apply_menu_overrides
chkeq "no override file -> RCONF_LOCALE unset" "${RCONF_LOCALE:-<unset>}" "<unset>"

# ===========================================================================
echo
echo "=== Test 2: clear is a no-op when no file exists ==="
state_clear_menu_overrides; chkrc "no-op clear rc=0" $? 0

# ===========================================================================
echo
echo "=== Test 3: apply sources values from the override file ==="
cat > "$TMPSTATE/menu-config.sh" <<'EOF'
RCONF_LOCALE=en_GB.UTF-8
RCONF_TIME_ZONE=Europe/London
ZRAM_PERCENT_OF_RAM=75
EOF
unset RCONF_LOCALE RCONF_TIME_ZONE ZRAM_PERCENT_OF_RAM
state_apply_menu_overrides
chkeq "RCONF_LOCALE applied"        "$RCONF_LOCALE"        "en_GB.UTF-8"
chkeq "RCONF_TIME_ZONE applied"     "$RCONF_TIME_ZONE"     "Europe/London"
chkeq "ZRAM_PERCENT_OF_RAM applied" "$ZRAM_PERCENT_OF_RAM" "75"

# ===========================================================================
echo
echo "=== Test 4: overrides win over baseline values ==="
RCONF_LOCALE="baseline-default"
state_apply_menu_overrides
chkeq "override wins" "$RCONF_LOCALE" "en_GB.UTF-8"

# ===========================================================================
echo
echo "=== Test 5: clear removes the override file ==="
[[ -f $TMPSTATE/menu-config.sh ]] && ok "file present before clear"
state_clear_menu_overrides
[[ ! -f $TMPSTATE/menu-config.sh ]] && ok "file removed after clear" || fail "file still present"

# ===========================================================================
echo
echo "=== Test 6: round-trip values containing spaces and metacharacters ==="
# This mirrors what menu_edit_config writes: printf '%s=%q\n' for safe quoting.
declare -A current=(
  [SIMPLE]="hello"
  [WITH_SPACES]="two words"
  [WITH_QUOTES]='he said "hi"'
  [WITH_SHELL_META]='$(rm -rf /)'
  [EMPTY_VAL]=""
)
{
  echo "# Generated by installicious menu_edit_config — runtime overrides for the current run."
  for key in "${!current[@]}"; do
    printf '%s=%q\n' "$key" "${current[$key]}"
  done
} > "$TMPSTATE/menu-config.sh"

unset SIMPLE WITH_SPACES WITH_QUOTES WITH_SHELL_META EMPTY_VAL
state_apply_menu_overrides
chkeq "SIMPLE round-trip"         "$SIMPLE"          "hello"
chkeq "WITH_SPACES round-trip"    "$WITH_SPACES"     "two words"
chkeq "WITH_QUOTES round-trip"    "$WITH_QUOTES"     'he said "hi"'
chkeq "WITH_SHELL_META preserved" "$WITH_SHELL_META" '$(rm -rf /)'
chkeq "EMPTY_VAL round-trip"      "${EMPTY_VAL-unset}" ""

state_clear_menu_overrides

# ===========================================================================
echo
echo "=== Test 7: chain precedence — role config overrides feature config ==="
# Simulates the source order menu_edit_config builds:
#   installicious.config  →  feature*.config  →  role*.config  →  menu-config.sh
# A key present in both feature.config and role.config must resolve to the
# role value (the rule is "role overrides feature").
TMPCFG=$(mktemp -d)
cat > "$TMPCFG/installicious.config" <<'EOF'
SHARED_KEY="from_installicious"
FEATURE_ONLY="from_installicious"
EOF
cat > "$TMPCFG/feature.config" <<'EOF'
SHARED_KEY="from_feature"
FEATURE_ONLY="from_feature"
ROLE_ONLY=""
EOF
cat > "$TMPCFG/role.config" <<'EOF'
SHARED_KEY="from_role"
ROLE_ONLY="from_role"
EOF

chkeq "feature-only key resolves to feature value" \
  "$(_menu_read_var_chain FEATURE_ONLY "$TMPCFG/installicious.config" "$TMPCFG/feature.config" "$TMPCFG/role.config")" \
  "from_feature"

chkeq "role-only key resolves to role value" \
  "$(_menu_read_var_chain ROLE_ONLY "$TMPCFG/installicious.config" "$TMPCFG/feature.config" "$TMPCFG/role.config")" \
  "from_role"

chkeq "shared key resolves to ROLE value (role wins)" \
  "$(_menu_read_var_chain SHARED_KEY "$TMPCFG/installicious.config" "$TMPCFG/feature.config" "$TMPCFG/role.config")" \
  "from_role"

# menu-config.sh wins over everything when present.
echo 'SHARED_KEY="from_user_edit"' > "$TMPSTATE/menu-config.sh"
chkeq "menu-config.sh overrides role value" \
  "$(_menu_read_var_chain SHARED_KEY "$TMPCFG/installicious.config" "$TMPCFG/feature.config" "$TMPCFG/role.config")" \
  "from_user_edit"
rm -rf "$TMPCFG"
state_clear_menu_overrides

# ===========================================================================
echo
echo "=== Test 8: menu-config.sh persists across simulated runs ==="
# Locks in the "edit once, keep forever" behavior: state_apply_menu_overrides
# must read previously-saved values without any framework helper clearing
# the file. The only way to wipe overrides is the explicit
# state_clear_menu_overrides call (or `rm` on the file).
rm -f "$TMPSTATE/menu-config.sh"
# Run-1: user enters values via the editor. menu_edit_config (whiptail-driven)
# can't be tested directly here, so we simulate its persistence step.
{
  echo "# Generated by installicious menu_edit_config — simulated for test."
  printf '%s=%q\n' "MOTD_WEATHER_API_KEY" "secret-bearer-abc123"
  printf '%s=%q\n' "MOTD_NAME" "alice"
} > "$TMPSTATE/menu-config.sh"

# Simulate end-of-run-1: nothing in the framework should auto-clear.
[[ -f "$TMPSTATE/menu-config.sh" ]] && ok "file present after run-1 (no auto-clear)" \
  || fail "menu-config.sh missing — something cleared it automatically"

# Run-2 startup: state_apply_menu_overrides should reload the values.
unset MOTD_WEATHER_API_KEY MOTD_NAME
state_apply_menu_overrides
chkeq "API key persisted across run"   "$MOTD_WEATHER_API_KEY" "secret-bearer-abc123"
chkeq "MOTD_NAME persisted across run" "$MOTD_NAME"            "alice"

# Manual reset still works on demand.
state_clear_menu_overrides
[[ ! -f "$TMPSTATE/menu-config.sh" ]] && ok "explicit clear removes file" \
  || fail "explicit clear did not remove file"

# ===========================================================================
echo
echo "=== Test 9: PATH_STATE fallback when not exported ==="
saved_path_state="$PATH_STATE"
unset PATH_STATE
mkdir -p state
echo 'FALLBACK_TEST="ok"' > state/menu-config.sh
unset FALLBACK_TEST
state_apply_menu_overrides
chkeq "fallback PATH_STATE=state" "$FALLBACK_TEST" "ok"
rm -f state/menu-config.sh
rmdir state 2>/dev/null
export PATH_STATE="$saved_path_state"

# ===========================================================================
echo
echo "=== Test 10: state_save_selections + state_load_selections roundtrip ==="
# Selections file lives at $PATH_STATE/selections.sh — distinct from
# menu-config.sh (which holds edited VALUES, not picks). This roundtrip
# locks in that save→load preserves role, role-tier picks, addons map,
# and the custom-flow features list.
unset LAST_ROLE_ID LAST_FEATURES_SELECTED LAST_ROLE_SPECIFIC_PICKED \
      LAST_OPTIONAL_PICKED LAST_PACKAGES_SELECTED LAST_ADDONS_PICKED
state_load_selections; chkrc "no file → rc=1" $? 1

state_save_selections \
  "weewx" \
  "" \
  "weewx-setup weewx-webroot weewx-site-ram neowx-material skyfield" \
  "locale bash motd compressed-swap ram-logging" \
  "" \
  "webserver:webserver-ssl;motd:motd-weather,motd-updates"
chkrc "state_save_selections rc=0" $? 0
[[ -f "$TMPSTATE/selections.sh" ]] && ok "selections.sh written" \
  || fail "selections.sh not created"

unset LAST_ROLE_ID LAST_FEATURES_SELECTED LAST_ROLE_SPECIFIC_PICKED \
      LAST_OPTIONAL_PICKED LAST_PACKAGES_SELECTED LAST_ADDONS_PICKED
state_load_selections; chkrc "load existing file → rc=0" $? 0
chkeq "LAST_ROLE_ID"               "$LAST_ROLE_ID"               "weewx"
chkeq "LAST_FEATURES_SELECTED"     "$LAST_FEATURES_SELECTED"     ""
chkeq "LAST_ROLE_SPECIFIC_PICKED"  "$LAST_ROLE_SPECIFIC_PICKED"  "weewx-setup weewx-webroot weewx-site-ram neowx-material skyfield"
chkeq "LAST_OPTIONAL_PICKED"       "$LAST_OPTIONAL_PICKED"       "locale bash motd compressed-swap ram-logging"
chkeq "LAST_PACKAGES_SELECTED"     "$LAST_PACKAGES_SELECTED"     ""
chkeq "LAST_ADDONS_PICKED"         "$LAST_ADDONS_PICKED"         "webserver:webserver-ssl;motd:motd-weather,motd-updates"

# ===========================================================================
echo
echo "=== Test 11: addons_picked serialize/deserialize roundtrip (in options.sh) ==="
# These helpers live in scripts/options.sh, not lib/state.sh. We re-define
# them here so the test exercises the actual format used at runtime.
declare -A addons_picked=()
addons_picked[webserver]="webserver-ssl"
addons_picked[motd]="motd-weather motd-updates"
addons_picked[somefeature]=""   # empty entries skipped

_serialize_addons_picked() {
  local out="" parent
  for parent in "${!addons_picked[@]}"; do
    [[ -z ${addons_picked[$parent]:-} ]] && continue
    [[ -n $out ]] && out+=";"
    out+="${parent}:${addons_picked[$parent]// /,}"
  done
  echo "$out"
}
_deserialize_addons_picked() {
  local serialized="$1" entry parent children
  local -a _entries
  IFS=';' read -ra _entries <<< "$serialized"
  for entry in "${_entries[@]}"; do
    [[ -z $entry ]] && continue
    parent="${entry%%:*}"
    children="${entry#*:}"
    children="${children//,/ }"
    addons_picked[$parent]="$children"
  done
}

serialized=$(_serialize_addons_picked)
# Order of associative-array keys isn't guaranteed; just check both entries
# are present and skip-empty fired.
echo "$serialized" | grep -q "webserver:webserver-ssl" && ok "webserver entry present" \
  || fail "webserver entry missing: $serialized"
echo "$serialized" | grep -q "motd:motd-weather,motd-updates" && ok "motd entry present" \
  || fail "motd entry missing: $serialized"
[[ "$serialized" != *"somefeature"* ]] && ok "empty 'somefeature' skipped" \
  || fail "empty entry leaked: $serialized"

# Roundtrip back through deserialize.
declare -A addons_picked=()
_deserialize_addons_picked "webserver:webserver-ssl;motd:motd-weather,motd-updates"
chkeq "deserialize webserver"  "${addons_picked[webserver]}"  "webserver-ssl"
chkeq "deserialize motd"       "${addons_picked[motd]}"       "motd-weather motd-updates"

# ===========================================================================
echo
echo "=== Test 12: configuration.override layering ==="
# overrides/configuration.override is a hand-authored KEY=VALUE file. It
# overrides config/*.config defaults but loses to the in-menu editor's
# menu-config.sh. Precedence: config < configuration.override < menu-config.sh
TMPOV=$(mktemp -d)
export PATH_OVERRIDES="$TMPOV"
rm -f "$TMPSTATE/menu-config.sh"
TMPCFG2=$(mktemp -d)
cat > "$TMPCFG2/feature.config" <<'EOF'
LAYER_KEY="from_config"
CONFIG_ONLY="from_config"
EOF

# (a) no override files → config value wins
chkeq "config value when no override" \
  "$(_menu_read_var_chain LAYER_KEY "$TMPCFG2/feature.config")" "from_config"

# (b) configuration.override beats config
echo 'LAYER_KEY="from_cfg_override"' > "$TMPOV/configuration.override"
chkeq "configuration.override beats config" \
  "$(_menu_read_var_chain LAYER_KEY "$TMPCFG2/feature.config")" "from_cfg_override"

# (c) menu-config.sh beats configuration.override
echo 'LAYER_KEY="from_menu"' > "$TMPSTATE/menu-config.sh"
chkeq "menu-config.sh beats configuration.override" \
  "$(_menu_read_var_chain LAYER_KEY "$TMPCFG2/feature.config")" "from_menu"

# (d) --skip-state drops menu-config.sh but KEEPS configuration.override
chkeq "--skip-state keeps configuration.override" \
  "$(_menu_read_var_chain LAYER_KEY --skip-state "$TMPCFG2/feature.config")" "from_cfg_override"

# (e) state_apply_menu_overrides layers the same way into the live env
unset LAYER_KEY CONFIG_ONLY
source "$TMPCFG2/feature.config"
state_apply_menu_overrides
chkeq "state_apply: menu edit wins"      "$LAYER_KEY"   "from_menu"
chkeq "state_apply: config-only intact"  "$CONFIG_ONLY" "from_config"

# (f) no menu-config.sh → state_apply lands on configuration.override
rm -f "$TMPSTATE/menu-config.sh"
unset LAYER_KEY
source "$TMPCFG2/feature.config"
state_apply_menu_overrides
chkeq "state_apply: override wins when no menu file" "$LAYER_KEY" "from_cfg_override"

rm -rf "$TMPOV" "$TMPCFG2"
unset PATH_OVERRIDES

echo
echo "=== Done ==="
