#!/bin/bash

# Module:      ZRAM Installer
# Description: Sets up compressed RAM swap (zram) using whichever manager fits
#              the OS:
#                - rpi-swap (preinstalled on Pi OS Trixie)
#                - zram-tools (Bullseye, Bookworm)
#              Disables dphys-swapfile (older SD-card swap) if present.
#              Configurable via config/zram.config.
#
# Bump II_VERSION to force a re-run on the next installicious run.
# The recorded config hash also forces a re-run if config/zram.config changes.

II_VERSION="1"
INSTALLER_ID="zram"
MODULE="ZRAM Installer"

source config/installicious.config || exit 1
source lib/log.sh
source lib/status.sh
source lib/apt.sh

FILE_CONFIG_ZRAM="$PATH_CONFIG/zram.config"
[[ -f $FILE_CONFIG_ZRAM ]] && source "$FILE_CONFIG_ZRAM"
ZRAM_PERCENT_OF_RAM="${ZRAM_PERCENT_OF_RAM:-50}"
ZRAM_COMPRESSION_ALGO="${ZRAM_COMPRESSION_ALGO:-zstd}"
ZRAM_SWAP_PRIORITY="${ZRAM_SWAP_PRIORITY:-100}"
ZRAM_DISABLE_DPHYS_SWAPFILE="${ZRAM_DISABLE_DPHYS_SWAPFILE:-true}"

if [[ -z $FILE_LOG_INSTALLICIOUS ]]; then
  FILE_LOG_INSTALLER="$PATH_LOGS/installicious.log"
else
  FILE_LOG_INSTALLER="$PATH_LOGS/$FILE_LOG_INSTALLICIOUS"
fi
log_init "$MODULE" "$FILE_LOG_INSTALLER"

if status_should_skip "$INSTALLER_ID" "$II_VERSION" "$FILE_CONFIG_ZRAM"; then
  log_info "Zram already configured at recorded version + config. Skipping."
  exit 0
fi

status_mark_started "$INSTALLER_ID"

fail() {
  log_fail "$1" "$2"
  status_mark_failed "$INSTALLER_ID" "$1 (code $2)"
  status_set "$(status_file_for "$INSTALLER_ID")" "ZRAM_STATUS" "Error"
  echo -e "[ \e[0;31mFAIL\e[0m ] Installicious could not configure ZRAM. Error Code: $2."
  exit "$2"
}

# Detect swap manager: rpi-swap (Pi OS Trixie) preinstalled, else zram-tools.
if dpkg -l rpi-swap 2>/dev/null | grep -q '^ii'; then
  SWAP_MANAGER="rpi-swap"
else
  SWAP_MANAGER="zram-tools"
fi
log_info "Detected swap manager: $SWAP_MANAGER."

if [[ $SWAP_MANAGER == "zram-tools" ]]; then
  apt_ensure_installed zram-tools
  rc=$?
  [[ $rc -ne 0 ]] && fail "Failed to install zram-tools." "$rc"
fi

if [[ $ZRAM_DISABLE_DPHYS_SWAPFILE == "true" ]] \
   && systemctl list-unit-files dphys-swapfile.service >/dev/null 2>&1 \
   && systemctl is-enabled --quiet dphys-swapfile 2>/dev/null; then
  log_info "Disabling dphys-swapfile (older SD-card swap)."
  sudo systemctl disable --now dphys-swapfile \
    || log_warn "Failed to disable dphys-swapfile (continuing)."
fi

# Reset live zram device(s) so the new config can be picked up without reboot.
zram_reset_devices() {
  sudo systemctl stop dev-zram0.swap 2>/dev/null || true
  sudo systemctl stop systemd-zram-setup@zram0.service 2>/dev/null || true
  local dev
  for dev in /dev/zram*; do
    [[ -b $dev ]] || continue
    if grep -q "^${dev} " /proc/swaps 2>/dev/null; then
      sudo swapoff "$dev" 2>/dev/null || true
    fi
  done
  if [[ -e /sys/block/zram0/reset ]] \
     && ! grep -qE "^/dev/zram0 " /proc/swaps /proc/mounts 2>/dev/null; then
    echo 1 | sudo tee /sys/block/zram0/reset >/dev/null 2>&1 || true
  fi
}

case $SWAP_MANAGER in
  rpi-swap)
    # rpi-swap-generator produces dev-zram0.swap from /etc/rpi/swap.conf[.d/*];
    # it owns size + mechanism but defers compression algo to
    # systemd-zram-setup@zram0.service which reads /etc/systemd/zram-generator.conf.
    # So we write both files.
    log_info "Writing /etc/rpi/swap.conf.d/99-installicious.conf."
    sudo mkdir -p /etc/rpi/swap.conf.d
    RAM_MULT=$(awk "BEGIN { printf \"%.2f\", $ZRAM_PERCENT_OF_RAM / 100 }")
    sudo tee /etc/rpi/swap.conf.d/99-installicious.conf >/dev/null <<EOF
# Generated by installicious install-zram. Edit config/zram.config and re-run.
[Main]
Mechanism=zram

[Zram]
RamMultiplier=${RAM_MULT}
EOF

    log_info "Writing /etc/systemd/zram-generator.conf for compression algo."
    sudo tee /etc/systemd/zram-generator.conf >/dev/null <<EOF
# Generated by installicious install-zram (algo for rpi-swap-managed zram0).
[zram0]
compression-algorithm = ${ZRAM_COMPRESSION_ALGO}
swap-priority = ${ZRAM_SWAP_PRIORITY}
EOF

    # zram-tools' zramswap.service would fight rpi-swap over /dev/zram0.
    if systemctl is-enabled --quiet zramswap.service 2>/dev/null; then
      log_info "Disabling zramswap.service (conflicts with rpi-swap)."
      sudo systemctl disable --now zramswap.service 2>/dev/null || true
    fi

    log_info "Reconfiguring /dev/zram0 to match new config."
    zram_reset_devices
    sudo systemctl daemon-reload
    sleep 1
    sudo systemctl start dev-zram0.swap 2>/dev/null \
      || log_warn "Live restart failed; reboot to pick up config cleanly."
    ;;

  zram-tools)
    log_info "Writing /etc/default/zramswap."
    sudo tee /etc/default/zramswap >/dev/null <<EOF
# Generated by installicious install-zram. Edit config/zram.config and re-run.
PERCENTAGE=${ZRAM_PERCENT_OF_RAM}
ALGO=${ZRAM_COMPRESSION_ALGO}
PRIORITY=${ZRAM_SWAP_PRIORITY}
EOF

    log_info "Restarting zramswap.service to apply config."
    zram_reset_devices
    sudo systemctl daemon-reload
    if ! sudo systemctl restart zramswap.service; then
      log_warn "zramswap.service restart returned non-zero; check 'systemctl status zramswap'."
    fi
    ;;
esac

log_ok "Zram swap configured (${SWAP_MANAGER}, ${ZRAM_PERCENT_OF_RAM}% of RAM, ${ZRAM_COMPRESSION_ALGO})."
status_mark_complete "$INSTALLER_ID" "$II_VERSION" "$FILE_CONFIG_ZRAM"
status_set "$(status_file_for "$INSTALLER_ID")" "ZRAM_STATUS" "Completed"
echo -e "[  \e[0;32mOK\e[0m  ] Installicious successfully configured ZRAM swap."
exit 0
